repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8

  - repo: https://github.com/ambv/black
    rev: v23.3.0
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
      - id: flake8

  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell

