project_config:
  task: classification
  work_dir: project/guoyao_kela
  topk: 2
  print_freq: 10

train_config:
  seed: 0
  epoch: 0
  max_epoch: 30
  print_freq: 10
  workflow: [[train, 1], [val, 1]]
  # workflow: [[val, 1]]
  deterministic: true
  scheduler_step_batch: true

model_config:
  model_name: shufflenet_v2_x1_0
  num_classes: 8
  pretrained: False
  model_path: project/guoyao_kela/weights/20230710(163402)_Epoch10_BestAcc98.0499_lr0.0_BestModel.pth
  gpu: 1 # -1==cpu
  strict: True
  map_location: cpu

classification_data_config:
  train:
    dataset_params:
      root: /media/seeking/data/llf/guoyao_kela/train
      wh: [420,240]
      letterbox: true
    dataloader_params:
      batch_size: 1024
      shuffle: False
      num_workers: 4
      pin_memory: True
      batch_sampler: BalancedBatchSampler #default:None

  val:
    dataset_params:
      root: /media/seeking/data/llf/guoyao_kela/val
      wh: [420,240]
      letterbox: true
    dataloader_params:
      batch_size: 48
      shuffle: false
      num_workers: 4
      pin_memory: True

optimizer_config:
  name: AdamW
  params:
    lr: 0.00003

lr_config:
  # name: LambdaLR
  # params:
  # lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 2

loss_config:
  loss_weights: null
  classification:
    CrossEntropyLoss: {}


ddp_config:
  flag: false
  batch_size: 64
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  test_dir: /media/seeking/data/llf/guoyao_kela/train/2_paoyanyichang
  # test_dir: /media/seeking/data/llf/gzsapa_dataset/segmentation/val
  weight: project/guoyao_kela/weights/20230710(163402)_Epoch10_BestAcc98.0499_lr0.0_BestModel.pth
  # batch_size: 1
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [0.05, 0, 0, 0, 0, 0]
  seg_threshold: [0, 36, 50, 36]
