#Project params-------------------------------------------------------------------------------------------------------
task_type: segmentation
project_path: project/shenghuo_back
seg_data_path: /home/seeking/llf/dataset/shenghuo_back/

wh: [ 256,256 ]
mean: [ 0.485,0.456,0.406 ]
std: [ 0.229,0.224,0.225 ]

#Model params-------------------------------------------------------------------------------------------------------
model_args:
  model_name: segmentation_shufflenetplus_v2_x1_0
  pretrained: false
  num_classes: 0
  mask_classes: 4
  resume:
    model_path: /home/seeking/llf/code/deep_learning_framework/project/shenghuo_back/weights/2023-04-28-(04:41:51)_MIoU:0.5705_best_model.pth
    strict: true
    map_location: cpu

#Trainging params-------------------------------------------------------------------------------------------------------
DDP_args:
  flag: false
  backend: nccl
  init_method: env://
  gpu: 0
  device: null
  batch_size: 32 #gpu_batch_size*num_gpu
  rank: 0
  local_rank: 0
  world_size: 1
  cuda_visible_device: [ 0,1 ]

seed: 0
benchmark: true
deterministic: false
num_workers: 8
gpu: 0
epochs: 1000
start_epoch: 0

batch_size: 256

losses_args:
  segmentation:
    PeriodLoss: { }
    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

letterbox_args:
  flag: false
  wh: [320,320]
  color: [114,114,114]

optimizer_args:
  name: AdamW
  params:
    lr: 0.02

lr_scheduler_args:
  name: LambdaLR
  params:
    lr_lambda: 'lambda epoch: 1 / (epoch / 4 + 1)' #impl this code
  
  # name: CosineAnnealingWarmRestarts
  # params:
    # T_0: 10
    # T_mult: 2

print_freq: 5
save_batch_checkpoint_flag: false

#Val params-------------------------------------------------------------------------------------------------------
top_k: 2
is_validate: true

#Test params-------------------------------------------------------------------------------------------------------
test:
  test_dir: ''
  need_classify_of_bad: true
  need_segment: true
  sum_method: true
  cls_threshold: [0, 1000,50,400 ]
  seg_threshold: [ 0,0 ]