project_config:
  task: classification
  work_dir: project/test_cls
  mlflow_uri: "localhost"
  mlflow_port: 5000
  experiment_name: "Demo"

train_config:
  topk: 2
  seed: 114514
  deterministic: true
  epoch: 0
  max_epoch: 1000
  print_freq: 10
  workflow: [ [ train, 1 ], [ val, 1 ] ]
#  scheduler_step_batch: false

model_config:
  model_name: shufflenet_v2_x1_0
  num_classes: 2
  pretrained: False
  model_path: ""
  gpu: 0 # -1==cpu
  strict: True
  map_location: cpu

classification_data_config:
  #---------------------------------------
  dataset:
    train:
      root: D:\llf\dataset\dog_cat\1280\train
      wh: [ 416,416 ]
      letterbox: true
    val:
      root: D:\llf\dataset\dog_cat\1280\train
      wh: [ 416,416 ]
      letterbox: true
  #---------------------------------------
  dataloader:
    train:
      batch_size: 8
      shuffle: False
      num_workers: 4
      pin_memory: True
      batch_sampler: BalancedBatchSampler #default:None
    val:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: True
  #---------------------------------------

optimizer_config:
  name: AdamW
  params: null
  lr: 0.001

lr_config:
  scheduler_step_in_batch: false
  #plan A
  name: LambdaLR
  optimizer: null
  lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  #---------------------------------------
  #plan B
  # name: CosineAnnealingWarmRestarts
  # optimizer: null
  # T_0: 10
  # T_mult: 2

loss_config:
  losses_weights: [ 1 ]
  classification:
    CrossEntropyLoss: { }

test_config:
  test_dir: D:\data\0danyang\20240123\loujian1
  #  test_dir: D:\data\0danyang\20240122\bad\E
  weight: D:\code\DLFv2\project\danyang_E_mt\weights\20240122_233416_Epoch21_Acc99.8881_MIoU0.7611_lr1.3e-05_BestModel.pth
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [ 0.2 , 0.85, 1, 0.9 ]
  #  cls_threshold: [ 0.9 , 0.1, 0.1, 0.1 ]
  #  seg_threshold: [ 0, 100, 40, 200 ,100,40 ]
  seg_threshold: [ 0 ]

