project_config:
  task: classification
  work_dir: project/classification
  topk: 2
  print_freq: 10

train_config:
  seed: 0
  epoch: 0
  max_epoch: 1000
  print_freq: 10
  # workflow: [ [ train,1 ] ]
  # workflow: [ [ val,1 ] ]
  workflow: [ [ train,1 ] ,[ val,1 ] ]
  deterministic: true
  scheduler_step_batch: false


model_config:
  model_name: shufflenet_v2_x1_0
  num_classes: 2
  pretrained: False
  model_path: project/gz_sapa_duanmian/weights/20230510(121026)_Epoch2_BestAcc83.6226_BestMIoU0.7951_BestModel.pth
  gpu: 0 # -1==cpu
  strict: True
  map_location: cpu

classification_data_config:
  train:
    dataset_params:
      root: '/home/seeking/llf/dataset/gz_sapa_jiayaosai_duanmian/classification/train'
      wh: [ 320,320 ]
      letterbox: true
    dataloader_params:
      batch_size: 64
      shuffle: True
      num_workers: 8
      pin_memory: True

  val:
    dataset_params:
      root: '/home/seeking/llf/dataset/gz_sapa_jiayaosai_duanmian/classification/train'
      wh: [ 320,320 ]
      letterbox: true
    dataloader_params:
      batch_size: 8
      shuffle: false
      num_workers: 4
      pin_memory: True


optimizer_config:
  name: AdamW
  params:
    lr: 0.001

lr_config:
  name: LambdaLR
  params:
    lr_lambda: 'lambda epoch: 1 / (epoch / 4 + 1)' #hook call

loss_config:
  loss_weights: null
  classification:
    CrossEntropyLoss: { }

ddp_config:
  flag: false
  batch_size: 32
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false
  # sync_performance: False


