project_config:
  task: segmentation
  work_dir: project/segmentation
  mlflow_uri: localhost
  mlflow_port: 5000
  mlflow_experiment_name: segmentation

train_config:
  topk: 2
  seed: 114514
  deterministic: true
  epoch: 0
  max_epoch: 100
  print_freq: 10
  workflow: [ [ train, 1 ], [ val, 1 ] ]
#  scheduler_step_batch: false

model_config:
  model_name: segmentation_shufflenetplus_v2_x1_0
  mask_classes: 2
  pretrained: False
  model_path: D:\llf\code\pytorch-lab\project\segmentation\runs\20240322_140331\weights\20240322_145757_Epoch54_Epoch54_MIoU#0.9248.pth
  gpu: 0 # -1==cpu
  strict: True
  map_location: cpu

segmentation_data_config:
  #---------------------------------------
  dataset:
    train:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 256,256 ]
      transform_resize: false
    val:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 256,256 ]
      transform_resize: false
  #---------------------------------------
  dataloader:
    train:
      batch_size: 16
      shuffle: False
      num_workers: 4
      pin_memory: True
    val:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: True
  #---------------------------------------

optimizer_config:
  name: AdamW
  params: null
  lr: 0.0001

lr_config:
  scheduler_step_in_batch: false
  #plan A
  #  name: LambdaLR
  #  optimizer: null
  #  lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  #---------------------------------------
  #plan B
  name: CosineAnnealingWarmRestarts
  optimizer: null
  T_0: 10
  T_mult: 2

loss_config:
  loss_weights: [ 1,0.5 ]
  segmentation:
    PeriodLoss:
      top_k: 0.5
      weight: [ 1,1 ]

    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

test_config:
  test_dir: D:\llf\dataset\danyang\F_train\seg\train
  weight: D:\llf\code\pytorch-lab\project\segmentation\runs\20240322_150546\weights\20240322_152042_Epoch15_epoch15_MIoU#0.9239.pth
  experiment_time: '20240322_150546'
  need_resize: False
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [ ]
  seg_threshold: [ ]

onnx_export_config:
  opset_version: 12
  model_path: ''
  output_name: 'segmentation.onnx'
  batch_size: 1
  input_h: 480
  input_w: 480
  channel: 3
  mask_classes: 3
  input_names: [ 'images' ]
  output_names: [ 'output' ]
  is_simplify: true
  verbose: false
  #----------------------------
  is_dynamic: true
  dynamic_axes:
    images:
      0: 'batch'
    output:
      0: 'batch'