project_config:
  task: segmentation
  work_dir: project/anbuping
  topk: 2
  print_freq: 10

train_config:
  seed: 0
  epoch: 0
  max_epoch: 100
  print_freq: 10
  # workflow: [[train, 1], [val, 1]]
  workflow: [[val, 1]]
  deterministic: true
  scheduler_step_batch: false

model_config:
  model_name: segmentation_shufflenetplus_v2_x1_0
  mask_classes: 3
  pretrained: False
  model_path: project/anbuping/weights/20230724(202627)_Epoch92_BestMIoU0.9051_lr3.4e-05_BestModel.pth
  gpu: 0 # -1==cpu
  strict: True
  map_location: cpu
  input_channels: 1

segmentation_data_config:
  train:
    dataset_params:
      root: /media/seeking/data/llf/anbuping/train
      wh: [320,768]
      img_mode: L
    dataloader_params:
      batch_size: 8
      shuffle: True
      num_workers: 1
      pin_memory: True

  val:
    dataset_params:
      root: /media/seeking/data/llf/anbuping/train
      wh: [320,768]
      img_mode: L
    dataloader_params:
      batch_size: 8
      shuffle: false
      num_workers: 1
      pin_memory: True

optimizer_config:
  name: AdamW
  params:
    lr: 0.001

lr_config:
  name: LambdaLR
  params:
    lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  # name: CosineAnnealingWarmRestarts
  # params:
  #   T_0: 10
  #   T_mult: 2

loss_config:
  loss_weights: [1, 0.5]

  segmentation:
    PeriodLoss:
      top_k: 0.5
      weight: [1, 1, 1]

    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

ddp_config:
  flag: false
  batch_size: 64
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  test_dir: /media/seeking/data/llf/gzsapa_dataset/classification/val/5_others
  # test_dir: /media/seeking/data/llf/gzsapa_dataset/segmentation/val
  weight: /home/seeking/llf/code/deep_learning_framework/project/gz_sapa/weights/20230614(165010)_Epoch16_BestAcc99.0377_BestMIoU0.9134_BestModel.pth
  # batch_size: 1
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [0.05, 0, 0, 0, 0, 0]
  seg_threshold: [0, 36, 50, 36]
