project_config:
  task: segmentation
  work_dir: project/danyang_F_seg_exp2
  topk: 2
  print_freq: 20

train_config:
  seed: 114514
  epoch: 0
  max_epoch: 20
  print_freq: 10
  workflow: [ [ train, 1 ], [ val, 1 ] ]
  # workflow: [[val, 1]]
  deterministic: true
  scheduler_step_batch: false

model_config:
  model_name: segmentation_shufflenetplus_v2_x1_0
  #  num_classes: 2
  mask_classes: 6
  pretrained: False
  model_path: D:\code\DLFv2\project\danyang_F_seg_exp2\weights\20240113_004538_Epoch51_MIoU0.9652_lr7e-06_BestModel.pth
  gpu: 0 # -1==cpu
  strict: true
  map_location: cpu

segmentation_data_config:
  train:
    dataset_params:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 256,256 ]
    dataloader_params:
      batch_size: 100
      shuffle: True
      num_workers: 1
      pin_memory: True

  val:
    dataset_params:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 256,256 ]
    dataloader_params:
      batch_size: 8
      shuffle: false
      num_workers: 1
      pin_memory: True
optimizer_config:
  name: AdamW
  params:
    lr: 0.0001

lr_config:
  name: LambdaLR
  params:
    lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
#  name: CosineAnnealingWarmRestarts
#  params:
#    T_0: 10
#    T_mult: 2

loss_config:
  loss_weights: [ 1, 0.5 ]

  segmentation:
    PeriodLoss:
      top_k: 0.5
      weight: [ 1, 1 ,1 ,1,1,1 ]

    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

ddp_config:
  flag: false
  batch_size: 128
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  test_dir: D:\data\0danyang\20240122\tmp\bad\F
  weight: D:\code\DLFv2\project\danyang_F_seg_exp2\weights\20240122_215705_Epoch44_MIoU0.9433_lr9e-06_BestModel.pth
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [ 0 ]
#  seg_threshold: [ 0,2000, 100, 100000, 100000,10000 ]
  seg_threshold: [ 0 ]
