#Default setting--------------------------------------------------------------------------------------------------------
mode: train           #train test
task: classification  #classification segmentation multitask
project: v3_classification #project_path or project_name
experiment: 'exp'

#Train setting----------------------------------------------------------------------------------------------------------
device: 0 #-1=cpu
seed: 0
topk: [ 1,2 ]
epochs: 100
workers: 2
workflow: [ [ train,1 ] , [ val,1 ] ]
model: shufflenet_v2_x1_0 #i.e. shufflenet_v2_x1_0 segmentation_shufflenetplus_v2_x1_0  multi_task_shufflenetplus_v2_x1_0
weight: 'model.pth'
pretrained: True
wh: [ 288,288 ]
amp: True
deterministic: True
preload: True

# Classification--------------------------------------------------------------------------------------------------------
classification:
  batch: 8
  classes: 2
  train: D:\llf\dataset\dog_cat\1280\train
  val: D:\llf\dataset\dog_cat\1280\val

# Segmentation----------------------------------------------------------------------------------------------------------
segmentation:
  batch: 8
  classes: 6
  train: 'D:\llf\dataset\danyang\training_data\E\seg'
  val: 'D:\llf\dataset\danyang\training_data\E\seg'

#Hyperparameters--------------------------------------------------------------------------------------------------------
optimizer: AUTO
cos_lr: True
lr0: 0.01 # (float) initial learning rate
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937
#FocalLoss alpha gamma
alpha: null
gamma: 0
loss_weights: [ 1,1 ] #[classification.weight segmentation.weight]

#Test setting-----------------------------------------------------------------------------------------------------------
test: ''
cls_thr: ''
seg_thr: ''

# MlFlow setting--------------------------------------------------------------------------------------------------------
mlflow_uri: localhost
mlflow_port: 5000
mlflow_experiment_name: classification
