#Default setting--------------------------------------------------------------------------------------------------------
mode: train           #train test
task: multitask  #classification segmentation multitask
project: v3project #project_path or project_name

#Train setting----------------------------------------------------------------------------------------------------------
device: 0 #-1=cpu
seed: 0
topk: 2
epochs: 10
workers: 2
workflow: [ { train: 1 } , { val: 1 } ]
model: shufflenet_v2_x1_0 #i.e. shufflenet_v2_x1_0 segmentation_shufflenetplus_v2_x1_0  multi_task_shufflenetplus_v2_x1_0
weight: ''
pretrained: True
wh: [ 480,480 ]
balanced_batch_sampler: True
preload: True

# Classification--------------------------------------------------------------------------------------------------------
classification:
  batch: 8
  classes: 3
  train: 'D:\dataset\cls\train100\train'
  val: 'D:\dataset\cls\train100\val'

# Segmentation----------------------------------------------------------------------------------------------------------
segmentation:
  batch: 8
  classes: 6
  train: 'D:\llf\dataset\danyang\training_data\E\seg'
  val: 'D:\llf\dataset\danyang\training_data\E\seg'

#Hyperparameters--------------------------------------------------------------------------------------------------------
optimizer: AUTO
cos_lr: True
lr0: 0.01 # (float) initial learning rate
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937
amp: True
deterministic: True
#FocalLoss alpha gamma
alpha: null
gamma: 0
loss_weights: [ 1,1 ] #[classification.weight segmentation.weight]



#Test setting-----------------------------------------------------------------------------------------------------------
test: ''
cls_thr: ''
seg_thr: ''

# MlFlow setting--------------------------------------------------------------------------------------------------------
mlflow_uri: localhost
mlflow_port: 5000
mlflow_experiment_name: multi_task
