#Default setting--------------------------------------------------------------------------------------------------------
mode: train           #train test
task: classification #classification segmentation multitask
project: project/v3 #project_path or project_name
experiment: 'exp'

#Train setting----------------------------------------------------------------------------------------------------------
seed: 0
topk: [ 1,2 ]
device: 0 #-1=cpu
epochs: 500
workers: 0
not_val: False
model: shufflenet_v2_x1_0
#model: segmentation_shufflenetplus_v2_x1_0
#model: multi_task_shufflenetplus_v2_x1_0
pretrained: True
weight: D:\llf\code\xTrainer\project\v3\exp.20240805_145806\weights\epoch20.pth
wh: [ 256,256 ]
amp: True
preload: True
deterministic: True
save_period: 5 # (int) Save checkpoint every x epochsa

# Classification--------------------------------------------------------------------------------------------------------
classification:
  batch: 16
  classes: 2
  train: D:\llf\dataset\dog_cat\64\train
  val: D:\llf\dataset\dog_cat\64\train

# Segmentation----------------------------------------------------------------------------------------------------------
segmentation:
  batch: 8
  classes: 3 #need background
  train: D:\llf\dataset\danyang\training_data\F\F
  val: D:\llf\dataset\danyang\training_data\F\F

#Hyperparameters--------------------------------------------------------------------------------------------------------
optimizer: auto
cos_lr: True
lr0: 0.0001 # (float) initial learning rate
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937
alpha: null #focal loss
gamma: 2 #focal loss
smooth: 1.0 #dice loss iou loss ce loss
loss_weights: [ 1,1 ] #cls_loss*w1+seg_loss*w2
seg_loss_weights: [ 0.5,1.0,1.0 ] #bce+dice+iou

#Test setting-----------------------------------------------------------------------------------------------------------
test: ''
cls_thr: ''
seg_thr: ''

# MlFlow setting--------------------------------------------------------------------------------------------------------
mlflow_uri: localhost
mlflow_port: 5000
mlflow_experiment_name: classification
