#Default setting--------------------------------------------------------------------------------------------------------
mode: train           #train test
task: classification  #classification segmentation multitask
project: project/v3_classification #project_path or project_name
experiment: 'exp'

#Train setting----------------------------------------------------------------------------------------------------------
seed: 0
topk: [ 1,2 ]
device: 0 #-1=cpu
epochs: 10
workers: 2
not_val: False
model: shufflenet_v2_x1_0 #i.e. shufflenet_v2_x1_0 segmentation_shufflenetplus_v2_x1_0  multi_task_shufflenetplus_v2_x1_0
pretrained: True
weight: model.pth
wh: [ 288,288 ]
amp: True
preload: True
deterministic: True
save_period: 2 # (int) Save checkpoint every x epochs
# Classification--------------------------------------------------------------------------------------------------------
classification:
  batch: 8
  classes: 2
  train: D:\llf\dataset\dog_cat\128\train
  val: D:\llf\dataset\dog_cat\128\train

# Segmentation----------------------------------------------------------------------------------------------------------
segmentation:
  batch: 2
  classes: 6
  train: 'D:\llf\dataset\danyang\training_data\E\seg'
  val: 'D:\llf\dataset\danyang\training_data\E\seg'

#Hyperparameters--------------------------------------------------------------------------------------------------------
optimizer: auto
cos_lr: True
lr0: 0.001 # (float) initial learning rate
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937
alpha: null
gamma: 0
loss_weights: [ 1,1 ] #[classification.weight segmentation.weight]

#Test setting-----------------------------------------------------------------------------------------------------------
test: ''
cls_thr: ''
seg_thr: ''

# MlFlow setting--------------------------------------------------------------------------------------------------------
mlflow_uri: localhost
mlflow_port: 5000
mlflow_experiment_name: classification
