#Default setting--------------------------------------------------------------------------------------------------------
mode: train           #train test
task: multitask #classification segmentation multitask
project: project/v3_segmentation #project_path or project_name
experiment: 'exp'

#Train setting----------------------------------------------------------------------------------------------------------
seed: 0
topk: [ 1,2 ]
device: 0 #-1=cpu
epochs: 100
workers: 0
not_val: False
#model: shufflenet_v2_x1_0
#model: segmentation_shufflenetplus_v2_x1_0
model: multi_task_shufflenetplus_v2_x1_0
pretrained: True
weight: model.pth
wh: [ 256,256 ]
amp: True
preload: False
deterministic: True
save_period: 2 # (int) Save checkpoint every x epochsa

# Classification--------------------------------------------------------------------------------------------------------
classification:
  batch: 8
  classes: 2
  train: D:\llf\dataset\dog_cat\128\train
  val: D:\llf\dataset\dog_cat\128\train

# Segmentation----------------------------------------------------------------------------------------------------------
segmentation:
  batch: 8
  classes: 4 #need background
  train: D:\llf\dataset\danyang\training_data\F\train
  val: D:\llf\dataset\danyang\training_data\F\train

#Hyperparameters--------------------------------------------------------------------------------------------------------
optimizer: auto
cos_lr: True
lr0: 0.001 # (float) initial learning rate
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937
alpha: null
gamma: 0
smooth: 1.0
loss_weights: [ 1,1 ] #cls_loss*w1+seg_loss*w2
seg_loss_weights: [ 0.5,1.0,1.0 ] #bce+dice+iou

#Test setting-----------------------------------------------------------------------------------------------------------
test: ''
cls_thr: ''
seg_thr: ''

# MlFlow setting--------------------------------------------------------------------------------------------------------
mlflow_uri: localhost
mlflow_port: 5000
mlflow_experiment_name: classification
