project_config:
  task: classification 
  work_dir: project/hrsf_zuo
  topk: 2
  print_freq: 10

train_config:
  seed: 0
  epoch: 0
  max_epoch: 100
  print_freq: 50
  workflow: [[train, 1], [val, 1]]
  # workflow: [[val, 1]]
  deterministic: true
  scheduler_step_batch: false

model_config:
  model_name: shufflenet_v2_x1_0
  num_classes: 11
  pretrained: False
  model_path: project/hrsf_zuo/weights/checkpoint.pth
  gpu: 1 # -1==cpu
  strict: True
  map_location: cpu

classification_data_config:
  train:
    dataset_params:
      root: /media/seeking/data/llf/hrsf/classification/train
      wh: [288,256]
      letterbox: true
    dataloader_params:
      batch_size: 64
      shuffle: False
      num_workers: 4
      pin_memory: True
      batch_sampler: BalancedBatchSampler #default:None

  val:
    dataset_params:
      root: /media/seeking/data/llf/hrsf/classification/val
      wh: [288,256]
      letterbox: true
    dataloader_params:
      batch_size: 32
      shuffle: false
      num_workers: 1
      pin_memory: True

optimizer_config:
  name: AdamW
  params:
    lr: 0.0003

lr_config:
  name: LambdaLR
  params:
    lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  # name: CosineAnnealingWarmRestarts
  # params:
  #   T_0: 10
  #   T_mult: 2

loss_config:
  loss_weights: null

  classification:
    CrossEntropyLoss: {}

ddp_config:
  flag: false
  batch_size: 128
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  # test_dir: /media/seeking/data/llf/gzsapa_xiansao/classification/val/1_qunbian
  # test_dir: /media/seeking/data/llf/gzsapa_xiansao/segmentation/val/6_pm-seg
#  test_dir: C:\Users\Lee Linfeng\Desktop\zuo_test
  test_dir: /media/seeking/data/llf/hrsf/classification/train/0_good
  # test_dir: /media/seeking/data/llf/gzsapa_dataset/segmentation/val
  # weight: project/gz_sapa_xiansao/weights/20230911(185625)_Epoch23_BestAcc99.587_BestMIoU0.9369_lr1.5e-05_BestModel.pth
#  weight: D:\llf\code\deep_learning_framework\project\hrsf_zuo\weights\20230922(144107)_Epoch1_BestAcc94.7396_lr0.000283_BestModel.pth
#  weight: D:\llf\code\deep_learning_framework\project\hrsf_zuo\weights\20230927_1_checkpoint.pth
  weight: project/hrsf_zuo/weights/checkpoint.pth
  # batch_size: 1
  good_idx: 0
  sum_method: true
  need_segment: false
  cls_threshold: [ 0.25 , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  seg_threshold: [ 0, 36, 50, 36 ]

