project_config:
  task: multitask
  work_dir: project/test_mt

train_config:
  topk: 2
  seed: 114514
  deterministic: true
  epoch: 0
  max_epoch: 10
  print_freq: 10
  workflow: [ [ train, 1 ], [ val, 1 ] ]
#  scheduler_step_batch: false

model_config:
  model_name: multi_task_shufflenetplus_v2_x1_0
  num_classes: 7
  mask_classes: 2
  pretrained: False
  model_path: D:\code\DLFv2\project\danyang_E_mt\weights\20240109_181429_Epoch12_Acc98.2616_MIoU0.8076_lr1.6e-05_BestModel.pth
  gpu: 0 # -1==cpu
  strict: True
  map_location: cpu

classification_data_config:
  #---------------------------------------
  dataset:
    train:
      root: D:\llf\dataset\danyang\G_train\train
      wh: [ 576,576 ]
      letterbox: true
    val:
      root: D:\llf\dataset\danyang\G_train\train
      wh: [ 576,576 ]
      letterbox: true
  #---------------------------------------
  dataloader:
    train:
      batch_size: 14
      shuffle: False
      num_workers: 1
      pin_memory: True
      batch_sampler: BalancedBatchSampler #default:None
    val:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: True
  #---------------------------------------

segmentation_data_config:
  #---------------------------------------
  dataset:
    train:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 576,576 ]
    val:
      root: D:\llf\dataset\danyang\F_train\seg\train
      wh: [ 576,576 ]
  #---------------------------------------
  dataloader:
    train:
      batch_size: 4
      shuffle: True
      num_workers: 1
      pin_memory: True
    val:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: True
  #---------------------------------------


optimizer_config:
  name: AdamW
  params: null
  lr: 0.00006

lr_config:
  scheduler_step_in_batch: false
  #plan A
  name: LambdaLR
  optimizer: null
  lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  #---------------------------------------
  #plan B
  # name: CosineAnnealingWarmRestarts
  # optimizer: null
  # T_0: 10
  # T_mult: 2

loss_config:
  losses_weights: [ 1,1, 0.5 ]
  classification:
    CrossEntropyLoss: { }
  segmentation:
    PeriodLoss:
      top_k: 0.5
      weight: [ 1, 1 ]
    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

#loss_config:
#  losses_weights: [ 1,1, 0.5 ]
#
#  classification:
#    CrossEntropyLoss: { }
#
#  segmentation:
#    PeriodLoss:
#      top_k: 0.5
#      weight: [ 1, 1 ,1,1,1,1 ]
#
#    DiceLoss:
#      model: MULTICLASS_MODE
#      log_loss: false
#      from_logits: true
#      smooth: 1
#      ignore_index: null
#      eps: 1.e-7

differential_learning_rates:
  used: false
  learning_rate: [ 0.001, 0.01, 0.1 ]

K_fold_cross_validation:
  used: false
  k: 5

weight_init:
  used: false
  func: kaiming_normal

ddp_config:
  flag: false
  batch_size: 128
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  test_dir: D:\data\0danyang\20240123\loujian1
  #  test_dir: D:\data\0danyang\20240122\bad\E
  weight: D:\code\DLFv2\project\danyang_E_mt\weights\20240122_233416_Epoch21_Acc99.8881_MIoU0.7611_lr1.3e-05_BestModel.pth
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [ 0.2 , 0.85, 1, 0.9 ]
  #  cls_threshold: [ 0.9 , 0.1, 0.1, 0.1 ]
  #  seg_threshold: [ 0, 100, 40, 200 ,100,40 ]
  seg_threshold: [ 0 ]

