project_config:
  task: multitask
  work_dir: project/danyang_E_mt_exp1
  topk: 2
  print_freq: 20

train_config:
  seed: 114514
  epoch: 0
  max_epoch: 1000
  print_freq: 10
  workflow: [ [ train, 1 ], [ val, 1 ] ]
#  workflow: [[val, 1]]
  deterministic: true
  scheduler_step_batch: false

model_config:
  model_name: multi_task_shufflenetplus_v2_x1_0
  num_classes: 4
  mask_classes: 5
  pretrained: False
  model_path: /home/main/llf/code/DLFv2/project/danyang_E_mt/weights/20240114_200539_Epoch49_Acc99.8739_MIoU0.7473_lr8e-06_BestModel.pth
  gpu: 1 # -1==cpu
  strict: True
  map_location: cpu
  only_load_backbone: false

classification_data_config:
  train:
    dataset_params:
      root: /home/main/llf/data/E_train/cls/train/576x576
      wh: [ 576,576 ]
      letterbox: true
    dataloader_params:
      batch_size: 32
      shuffle: False
      num_workers: 1
      pin_memory: True
      batch_sampler: BalancedBatchSampler #default:None
  val:
    dataset_params:
      root: /home/main/llf/data/E_train/cls/train/576x576
      wh: [ 576,576 ]
      letterbox: true
    dataloader_params:
      batch_size: 16
      shuffle: false
      num_workers: 0
      pin_memory: True
segmentation_data_config:
  train:
    dataset_params:
      root: /home/main/llf/data/E_train/seg/576x576_exp1
      wh: [ 576,576 ]
#      wh: [ 928,928 ]
    dataloader_params:
      batch_size: 4
      shuffle: True
      num_workers: 1
      pin_memory: True

  val:
    dataset_params:
      root: /home/main/llf/data/E_train/seg/576x576_exp1
      wh: [ 576,576 ]
#      wh: [ 928,928 ]
    dataloader_params:
      batch_size: 2
      shuffle: false
      num_workers: 0
      pin_memory: True

optimizer_config:
  name: AdamW
  params:
    lr: 0.001

lr_config:
  name: LambdaLR
  params:
    lr_lambda: "lambda epoch: 1 / (epoch / 4 + 1)" #hook call
  # name: CosineAnnealingWarmRestarts
  # params:
  #   T_0: 10
  #   T_mult: 2

loss_config:
  loss_weights: [ 1,1, 0.5 ]

  classification:
    CrossEntropyLoss: { }

  segmentation:
    PeriodLoss:
      top_k: 0.5
      weight: [ 1, 1 ,1,1,1]

    DiceLoss:
      model: MULTICLASS_MODE
      log_loss: false
      from_logits: true
      smooth: 1
      ignore_index: null
      eps: 1.e-7

ddp_config:
  flag: false
  batch_size: 128
  num_workers: 8
  backend: nccl
  init_method: env://
  rank: 0
  local_rank: 0
  world_size: 1
  # cuda_visible_device: [ 0,1 ]
  sync_bn: false

test_config:
  test_dir: D:\data\danyang\20240111\1.11bad\bad\E\0
  weight: D:\code\DLFv2\project\danyang_E_mt\weights\20240110_190327_Epoch7_Acc99.753_MIoU0.7599_lr2.4e-05_BestModel.pth
  good_idx: 0
  sum_method: true
  need_segment: true
  cls_threshold: [ 0.2 , 0.85, 1, 0.9]
  seg_threshold: [ 0, 100, 40, 200 ,100,40]

